### PR TITLE
Updated unrar source to 5.4.5 and added new function listVolumePaths

### PR DESCRIPTION
**Pull request by aonez**
Public function listVolumePaths returns all paths from a rar file. Very rudimentary, more UnrarKit knowledge devs can make a faster procedure.

### CODE REVIEW

**Comment by abbeycode** [comment]
Thanks for the contribution. I'll check it out when I get a chance. Can you tell me the difference though between your new `listVolumePaths` and the existing `listFilenames`?

**Comment by aonez** [comment]
`listVolumePaths` lists the paths of the volumes, not the contents of the file.
For example, a rar file **example.part1.rar** and **example.part2.rar** will return:

- <path_to>/example.part1.rar
- <path_to>/example.part2.rar

**Comment by aonez** [comment]
Only works with used and next volumes. For example if I use **example.part2.rar,** it will list *.part3.rar, *.part4.rar and so on, but no *.part1.rar.

**Comment by aonez** [comment]
Maybe getting this info will get the first part path:
https://github.com/abbeycode/UnrarKit/blob/master/Libraries/unrar/extract.cpp#L124

**Comment by abbeycode** [comment]
I updated the UnRAR version myself on `master`. Can you please rebase your PR so we can focus on the new function you want to add?

**Comment by aonez** [comment]
I'm having problems since your update. I'm having "use of @import when modules are disabled". Any idea why?

**Pull request closed without merging**
