### PR TITLE
unrarlib updated to v 6.1.7

### PR DESCRIPTION
**Pull request by gpotari**
unrarkit has been updated to the latest version (v6.12)
_(link: http://www.rarlab.com/rar/unrarsrc-6.0.7.tar.gz)_

### CODE REVIEW

**Comment by gpotari** [comment]
is it possible to exclude isnt.cpp from cocoapod source files. (podspec) It would solve the error above

**Comment by abbeycode** [comment]
I think this is what you're looking for. Remove the line below:

https://github.com/abbeycode/UnrarKit/blob/v2.11/UnrarKit.podspec#L44

However, I would say if you're excluding it from the pod spec, you should also exclude it from the `unrar` compilation target in the project.

**Comment by gpotari** [comment]
Thank you, I did so. All checks have passed.

**Comment by gpotari** [comment]
Thank you, I did so. All checks have passed.

**Review by abbeycode — CHANGES_REQUESTED** [review]
Looking good! Just a few minor things before merging:

- [ ] Add a line to CHANGELOG.md about upgrading the library [see here](https://github.com/abbeycode/UnrarKit/blob/v2.11/CHANGELOG.md?plain=1#L14), adding a credit to yourself like in PR 101
- [ ] I'm glad you added the 4 new files to the `unrar` group in the project, but can you please drag them down to their correct alphabetical places to stay consistent with the rest of their group?
- [ ] Where did you get the v6.12 version number from? When I download the latest source [from RARLAB](https://www.rarlab.com/rar_add.htm), I'm seeing it as 6.1.7. I think we should probably be consistent with that

Thanks again for taking this on!

**Comment by gpotari** [comment]
> Looking good! Just a few minor things before merging:
> 
> * [x]  Add a line to CHANGELOG.md about upgrading the library [see here](https://github.com/abbeycode/UnrarKit/blob/v2.11/CHANGELOG.md?plain=1#L14), adding a credit to yourself like in PR 101

Changelog updated 

> * [x]  I'm glad you added the 4 new files to the `unrar` group in the project, but can you please drag them down to their correct alphabetical places to stay consistent with the rest of their group?

alphabetical order updated

> * [x]  Where did you get the v6.12 version number from? When I download the latest source [from RARLAB](https://www.rarlab.com/rar_add.htm), I'm seeing it as 6.1.7. I think we should probably be consistent with that

I know it is confusing but if you download the library from  [this](http://www.rarlab.com/rar/unrarsrc-6.1.7.tar.gz) link, and if you open up version.hpp, it says the version number is 6.12.0
Screenshot 2022-07-25 at 09 47 16

> 
> Thanks again for taking this on!

Thank you

**Comment by abbeycode** [comment]
Thanks for that explanation. You pointed to the same link that I shared, and I think I understand now where the 6.12 is coming from - it's the RAR application version number. The library is numbered separately, and I always take that number from the name of the archive containing the source, so let's use 6.1.7 consistently everywhere (like in the CHANGELOG file update) then we'll be good to go.

**Comment by gpotari** [comment]
Updated

**Comment by abbeycode** [comment]
Thanks again! All merged!

**Pull request merged**
